# Generated by Django 2.2.1 on 2019-05-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insert_tu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.PositiveIntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_seq', models.PositiveIntegerField()),
                ('chapter_id', models.PositiveIntegerField()),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_seq', models.PositiveIntegerField()),
                ('goal_id', models.PositiveIntegerField()),
                ('goal_name', models.CharField(max_length=200)),
                ('goal_seq', models.PositiveIntegerField()),
                ('tu_id', models.PositiveIntegerField()),
                ('tu_name', models.CharField(max_length=200)),
                ('mapping_type', models.CharField(max_length=100)),
            ],
        ),
    ]
