# Generated by Django 2.2.1 on 2019-05-21 13:40

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mapping',
        ),
        migrations.DeleteModel(
            name='tu_lo',
        ),
        migrations.DeleteModel(
            name='tu_video',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage=pages.models.OverwriteStorage(), upload_to='documents/'),
        ),
    ]
